### ISSUE TITLE
Implement Model's program finding and running functions

### ISSUE THREAD

**Issue by CsullogBeni** [CsullogBeni/szofttech#29]
Implement:
- __find_all_runnable, it should collect all runnable from working_dir, and also collect all FileInfo.
- _find_all_runnable should call the add_working_directory_path with the current __working_directory_path, because it's solves the problem above
- run_program, that should execute a command string. (use subprocess library, run should work).
- given param command should look like this: "{full path} {arg1} {arg1 value} {...}"
- subprocess.run(f"python { command}) should work. This will use the actual python (actual interpreter).

**Comment by laczkozsofi** [comment]
Marci has written a function for the task of __find_all_runnable, so I have done only run_program method
