### ISSUE TITLE
Data access working directory addition

### ISSUE THREAD

**Issue by CsullogBeni** [CsullogBeni/szofttech#33]
- Implement a function that saves and loads the Model's working directory property. 
- The function takes a full path as param, and that string should be saved into a json file in app data dir. 
- Do related changes in Model class.
- In Model ctor the new load function should be called, and if it returns a full path, the working_dir variable should be the function's return value.
- Do related changes in drawio files and in imgs.

**Comment by laczkozsofi** [comment]
@CsullogBeni please help me a little.
I don't really understand should it be one function. Is it okay, if I write one function which saves the Model's working directory property, and one which loads it?
